ALTER TABLE book ADD COLUMN IF NOT EXISTS total_word_count INTEGER;
ALTER TABLE book ADD COLUMN IF NOT EXISTS cover_image_path VARCHAR(1024);
ALTER TABLE book ADD COLUMN IF NOT EXISTS visibility_status VARCHAR(50) DEFAULT 'PRIVATE' NOT NULL;
ALTER TABLE book ADD COLUMN IF NOT EXISTS author_name VARCHAR(255);
ALTER TABLE book ADD COLUMN IF NOT EXISTS genre VARCHAR(100);
ALTER TABLE book ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE book ADD COLUMN IF NOT EXISTS published_date_text VARCHAR(50);
ALTER TABLE book ADD COLUMN IF NOT EXISTS total_pages INTEGER;
ALTER TABLE book ADD COLUMN IF NOT EXISTS vision_batch_size INTEGER DEFAULT 100;
